name: Feature idea
description: Suggest a new idea
labels: [feature, needs triage]
body:
- type: textarea
  attributes:
    label: "Feature summary:"
    description: |
      A detailed and concise description for the feature proposed.
  validations:
    required: true
- type: textarea
  attributes:
    label: "Proposal & Constraints:"
    description: |
      What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?
      Which suggestions or requirements should be considered for how the feature needs to appear or be implemented?
  validations:
    required: false
- type: textarea
  attributes:
    label: "Additional context:"
    description: |
      Add any other context or screenshots about the feature request here.
  validations:
    required: false
    
